### ISSUE TITLE
Caught SIGSEGV when trying to start on Fedora 27

### ISSUE THREAD

**Issue by DcR-NL** [L3vi47h4N/Viper4Linux#1]
I'm trying to get this to run on Fedora 27 (and yes I'm a linux noob, but I'm eager to learn). Maybe somebody can help me out.

# Fedora specific
This are all the different commands I had to run compared to the current README.

## Dependencies
```sudo dnf install @development-tools gstreamer1 gstreamer1-devel gstreamer1-plugins-base-devel gstreamer1-plugins-bad-free-devel autoconf automake libtool```

This means I'm using **gstreamer 1.12.4-1.fc27**. Could this be (one of) the issue(s)?

## Installing the plugin
`sudo cp libgstviperfx.so /usr/lib64/gstreamer-1.0/`

# Problem
The viper script seems to throw a SIGSEGV, but I do see the viper sink after starting:
```
--
        Name: alsa_output.pci-0000_00_1b.0.analog-stereo
        Description: Intern geluid Analoog stereo
--
        Name: viper
        Description: Viper4Linux
```
## Run output
```
$ viper start
Setting original sink to full volume...
Changing primary sink to Viper...
$ Caught SIGSEGV
Spinning.  Please run 'gdb gst-launch-1.0 7217' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
^C
```
```
$ viper status
Not yet fully implemented.
There is a pidfile. Gstreamer may be running at pid: 7217.
There is an idfile. The viper sink seems to be loaded at id: 52.
```

Any idea how to debug this? The viper.log seems to be empty.

**Comment by DcR-NL** [comment]
Sorry, opened the issue with an empty description (too excited, I guess)... Updated it now.

**Comment by corrpel** [comment]
First of all, you are awesome for putting this together.
Tried it today on Ubuntu and man, the sound is so good now.
I've tried to make it work on a arm box, but:
Same issue here.
Caught SIGSEGV

Reading symbols from gst-launch-1.0...(no debugging symbols found)...done.
Attaching to program: /usr/bin/gst-launch-1.0, process 9241
Reading symbols from /usr/lib/aarch64-linux-gnu/libgstreamer-1.0.so.0...(no debugging symbols found)...done.
Reading symbols from /usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0...(no debugging symbols found)...done.
Reading symbols from /lib/aarch64-linux-gnu/libglib-2.0.so.0...(no debugging symbols found)...done.
Reading symbols from /lib/aarch64-linux-gnu/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Reading symbols from /lib/aarch64-linux-gnu/libc.so.6...(no debugging symbols found)...done.
Reading symbols from /lib/ld-linux-aarch64.so.1...(no debugging symbols found)...done.
Reading symbols from /usr/lib/aarch64-linux-gnu/libgmodule-2.0.so.0...(no debugging symbols found)...done.
Reading symbols from /lib/aarch64-linux-gnu/libm.so.6...(no debugging symbols found)...done.
Reading symbols from /lib/aarch64-linux-gnu/libdl.so.2...(no debugging symbols found)...done.
Reading symbols from /usr/lib/aarch64-linux-gnu/libffi.so.6...(no debugging symbols found)...done.
Reading symbols from /lib/aarch64-linux-gnu/libpcre.so.3...(no debugging symbols found)...done.
Reading symbols from /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstviperfx.so...done.
Reading symbols from /usr/lib/aarch64-linux-gnu/libgstaudio-1.0.so.0...(no debugging symbols found)...done.
Reading symbols from /usr/lib/aarch64-linux-gnu/libgstbase-1.0.so.0...(no debugging symbols found)...done.
Reading symbols from /usr/lib/aarch64-linux-gnu/libgsttag-1.0.so.0...(no debugging symbols found)...done.
Reading symbols from /usr/lib/aarch64-linux-gnu/liborc-0.4.so.0...(no debugging symbols found)...done.
Reading symbols from /lib/aarch64-linux-gnu/libz.so.1...(no debugging symbols found)...done.
0x0000007f9b4ef1e4 in __nanosleep_nocancel () from /lib/aarch64-linux-gnu/libpthread.so.0


Any help is highly appreciated :)

**Comment by L3vi47h4N** [comment]
Just dropping this message here so you know I've seen it. I'll try to get to it shortly!

**Comment by DcR-NL** [comment]
@L3vi47h4N Thanks for taking the time. No, I'm using a x64 CPU (Intel i7 4790).

**Comment by L3vi47h4N** [comment]
@DcR-NL alright it seems you and @corrpel may have separate issues then. Unfortunately for corrpel, the only library I was provided was precompiled for amd64 systems, we have options for trying to get things working on ARM such as attempting to leverage the android library or asking the dev for an arm variant. 

Now to your issue, what are the basics around your system? Mostly vanilla install? 

I'll have to recreate your environment to diagnose this so if I could get the following I would appreciate it. 

Distro version:
GUI stack: (gdm/gnome, sddm/kde, etc)
Any pulseaudio mods: 
Number of audio output devices: (probably just 1, maybe 2)
Anything else you may think is relevant: (your initial info was pretty detailed so I don't expect much here)

If you run `gst-inspect/gst-inspect1.0 viperfx` what do you get?

**Comment by DcR-NL** [comment]
I don't know what happened here, but 8 days have passed since my last try and now I'm not seeing the _Caught SIGSEGV_ any more. Maybe because of an update or just the (multiple) reboots...  Sadly it still does not seem to work for me. Also tried recompiling.

The current output: 
```
$ viper start
Setting original sink to full volume...
Changing primary sink to Viper...
$ 
```

Tried validating the processing by lowering all the equalizer values inside the audio.cfg:
```
eq_enable=true
eq_band1=-1200
eq_band2=-1200
eq_band3=-1200
eq_band4=-1200
eq_band5=-1200
eq_band6=-1200
eq_band7=-1200
eq_band8=-1200
eq_band9=-1200
eq_band10=-1200
```
And restarting viper (`viper restart)` But I'm not hearing changes to the audio output.

# Your request

> Now to your issue, what are the basics around your system? Mostly vanilla install?

Yes, it's 'just' a development machine. Java SDKs, NodeJS, Intellij, well, I think you got the picture...

> Distro version:

 [Fedora 27 KDE Plasma Desktop Edition](https://spins.fedoraproject.org/kde/download/index.html)
> GUI stack:

KDE
> Any pulseaudio mods:

Not that I know of
> Number of audio output devices: (probably just 1, maybe 2)

Two outputs. Trying to get it to work for Sink 1, not 0: [gist of `pactl list sinks` output](https://gist.github.com/DcR-NL/6b4e71395a2962a5eb2beec5dfd6ea44#file-gistfile1-txt).

> Anything else you may think is relevant: (your initial info was pretty detailed so I don't expect much here)

My audio.cfg: 
`desc="Speakers" location=alsa_output.pci-0000_00_1b.0.analog-stereo`

[Gist of viper.log output](https://gist.github.com/DcR-NL/3d122551ac77ad1a7c38d45efcd6fc95#file-gistfile1-txt).

> If you run gst-inspect/gst-inspect1.0 viperfx what do you get?

I assume you mean `gst-inspect-1.0 viperfx`. [Gist of output](https://gist.github.com/DcR-NL/b6b9dc6239fb8ab83ba7fc75bb828c38#file-gistfile1-txt).

**Comment by L3vi47h4N** [comment]
@DcR-NL Did you install BOTH .so files? There is a system library that goes in /lib in addition to the gstreamer library you compile. I am just getting around to testing this in a VM sorry.

**Comment by Qbunjo** [comment]
Hi there,
did you managed SIGSERV error on ARM machines? I just compiled the library, but it throws up with an error:
` ./viper start
Killed process. Deleted pidfile.
Unloaded Viper sink.
Setting original sink to full volume...
Changing primary sink to Viper...
Moving existing audio streams to Viper...
qbunjo@JackOfCards:~/Viper4Linux$ Caught SIGSEGV
Spinning.  Please run 'gdb gst-launch-1.0 15676' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.`
However, when I check on that `./viper status`
it says, there is a process and viper sink seems to be loaded.
