### ISSUE TITLE
More documentation?

### ISSUE THREAD

**Issue by dubbadubbadubbacha** [L3vi47h4N/Viper4Linux#10]
Sorry if this is the wrong place but is there more documentation on how to edit the audio.conf file? I have no idea what the abbreviations mean. I would like to add more bass and diable the surround effect which is leaning to one channel.

**Comment by L3vi47h4N** [comment]
take a look at `gst-inspect-1.0 viperfx` for more information. You can also help out with the work going on here: https://github.com/L3vi47h4N/Viper4Linux-Configs/pull/1 which is trying to add more information to the template audio.conf
