### ISSUE TITLE
SIGSERV on ARM machines

### ISSUE THREAD

**Issue by Qbunjo** [L3vi47h4N/Viper4Linux#11]
Hello,
did you managed SIGSERV error on ARM machines? I just compiled the library, but it throws up with an error:
$` ./viper start
Killed process. Deleted pidfile.
Unloaded Viper sink.
Setting original sink to full volume...
Changing primary sink to Viper...
Moving existing audio streams to Viper...
$~/Viper4Linux$ Caught SIGSEGV
Spinning.  Please run 'gdb gst-launch-1.0 15676' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.` 
However, when I check on that 
`./viper status` it says, there is a process and viper sink seems to be loaded.
I don't know if it eventually works, or not? If there is an error, I suppose, it doesn't.

The machine is Orange Pi Zero with Armbian (Debian for arm devices).

_Originally posted by @Qbunjo in https://github.com/L3vi47h4N/Viper4Linux/issues/1#issuecomment-433881467_

**Comment by L3vi47h4N** [comment]
The proprietary library I use from the original Viper devs is only built for x86_64 systems. I cannot support arm without another library.
