### ISSUE TITLE
Created Fork to test dynamic system

### ISSUE THREAD

**Issue by alexruedi** [L3vi47h4N/Viper4Linux#12]
https://github.com/alexruedi

If you like it, please feel free to copy the changes. I can make my repo private, if you include the changes. You can also change it to load it from config, just change in Viper4Linux/viper the dynsys parameters to

dynsys-enable="$dynsys_enable" dynsys-ycoeffs="$dynsys_ycoeffs" dynsys-sidegain="$dynsys_sidegain" dynsys-xcoeffs="$dynsys_xcoeffs" dynsys-bassgain="$dynsys_bassgain"

**Comment by L3vi47h4N** [comment]
Looks good! I've got some friends in the Viper4Android developer community that may know the correct min/max values for these variables. I'll see if we can find these. Thanks!

**Comment by alexruedi** [comment]
Thank you. I think the description could be useful as well. Aynway did you test it?

To me it looks like removed on purpose, but the one who did it missed some..

**Comment by L3vi47h4N** [comment]
I have not had the chance to test it yet. The original gstreamer plugin was made by the viper devs, I don't know why this feature was left out. I'll test it once I get the chance, and if it turns out to be stable, then I'm all for new features! Thanks again, I'll keep you posted.

**Comment by alexruedi** [comment]
Me neither, but it was missing in Viper4Windows as well... 

I couldn't ever create the repo you did, so all thanks goes to you. If you want to try without changing anything, you can boot to live ubuntu 16.04 and run instructions attached. (All you need is network access, once booted)

[instructions.txt](https://github.com/L3vi47h4N/Viper4Linux/files/2546000/instructions.txt)
It will have it enabled by default, change the values in Viper4Linux/viper on line 36, col 671.

**Comment by alexruedi** [comment]
Would you mind to confirm the new functionality?

Min/Default/Max values and description would make it complete.

**Comment by L3vi47h4N** [comment]
I still haven't had a chance mate. Sorry. My day job is kinda killer. Until I get the chance to look into this more, we could see about having a "dynamic system" branch. Then as I test we can merge things into the main.

**Comment by L3vi47h4N** [comment]
@alexruedi it looks like your fork was detached from my project. This makes it difficult for me to compare branches. Can you please download your project, refork mine, and push your changes to your fork? I can then start merging the changes over. https://stackoverflow.com/questions/36225381/reattach-a-detached-fork-in-github

**Comment by L3vi47h4N** [comment]
This was implemented after some ups and downs. Thanks @thepbone.
