### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by lds1998** [L3vi47h4N/Viper4Linux#14]
I used yay -S viper4linux-git to get most of the work done.
then configured device.conf with desc="Speakers" location=alsa_output.pci-0000_00_1f.3.analog-stereo
When started viper gives this: 

Setting original sink to full volume...
Changing primary sink to Viper...
Moving existing audio streams to Viper...
WARNING: erroneous pipeline: no element "pulsesrc"

If asked for a status:
[ERROR]
There is a pidfile. However, there is no process running with the expected pid.
There is an idfile. The viper sink seems to be loaded at id: 98.

OS: Manjaro Linux

**Comment by yochananmarqos** [comment]
Remove the device.conf and try again. It shouldn't be normally necessary unless the default sound device bis not detected.

**Comment by lds1998** [comment]
Just removed the device.conf file and problem remains.

**Comment by yochananmarqos** [comment]
I'm using Manjaro as well and I can't reproduce it. Are you sure the dependencies were installed?

**Comment by lds1998** [comment]
I just rebooted the computer and well the problem fix itself all. Thank you anyway.
Should I delete this?

**Comment by yochananmarqos** [comment]
You can close the issue.

**Comment by L3vi47h4N** [comment]
Thanks for taking care of this @yochananmarqos
