### ISSUE TITLE
Works on ubuntu1804 after using the following commands

### ISSUE THREAD

**Issue by robmsmt** [L3vi47h4N/Viper4Linux#6]
Great plugin, i found that i was missing the following:

sudo apt-get install libgstreamer1.0-dev 
sudo apt-get install libgstreamer-plugins-base1.0-dev

These were required to get ./autogen.sh to run.

Best,
Rob

**Comment by L3vi47h4N** [comment]
Thanks for the info! I'll take a look and update the Readme accordingly once I get some downtime!

**Comment by L3vi47h4N** [comment]
Added this info to the readme with commit: https://github.com/L3vi47h4N/Viper4Linux/commit/cd8847bfe95276c698424822a33d7ee0c458a824

Thanks for the info!
