### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by cxyzzz** [L3vi47h4N/Viper4Linux#7]
im install as aur,when run viper start, it display that

┌─[virgo@virgo-pc] - [~] - [四 9月 27, 22:53]
└─[$] <> viper start          
Setting original sink to full volume...
Changing primary sink to Viper...
Moving existing audio streams to Viper...
WARNING: erroneous pipeline: could not set property "eq-band1" in element "viperfx0" to "4.5"

os：manjaro

my /etc/viper4linux/devices.conf :
desc="Speakers" location=alsa_output.pci-0000_00_1b.0.analog-stereo

**Comment by L3vi47h4N** [comment]
I am going to go ahead and close this pending updates. I am guessing there is an error in your audio.conf where you have set a decimal value of "4.5" when it only supports whole numbers.
