### ISSUE TITLE
no element "device"

### ISSUE THREAD

**Issue by Baerbeisser** [L3vi47h4N/Viper4Linux#9]
Hi, thanks for your work.
System: Artix Linux (Arch) with XFCE
Language: German

### Installation:
I installed viper4linux-git from AUR.
It depends on

- gst-plugin-viperfx-git
- libviperfx-nonfree-bin

After that, it said `no element "pulsesrc"`

I googled quite a bit to find that i had to install

- gst-plugins-good

Could you add it to your readme as dependency for Arch?

### The issue:
with `pactl list sinks | grep "Name: "` i get
```
Name: alsa_output.pci-0000_28_00.1.hdmi-stereo-extra1
Name: alsa_output.pci-0000_2a_00.3.analog-stereo
```
After first time starting viper, there was no folder "viper4linux" in .config, so i created it.
Following your readme, i added 
```
desc="Speakers" 
location=alsa_output.pci-0000_2a_00.3.analog-stereo
```
but i get
```
~]$ viper start
Setting original sink to full volume...
Sie müssen einen Senkennamen/-Indexwert und einen Portnamen angeben
Changing primary sink to Viper...
Moving existing audio streams to Viper...
~]$ WARNUNG: Fehlerhafte Leitung: Kein Element »device«
```
So, is the format of the sinkname wrong? What portname?

**Comment by L3vi47h4N** [comment]
Regarding the dependency, is this a dependency that is automatically satisfied if following the manual installation steps? If so, I will pass this onto the maintainers of the AUR package, if not, I'll add it and also pass on that info. 

I'll edit once I read the rest.

**Comment by Baerbeisser** [comment]
No, viper4linux-git says something like `dependency gst-plugin-viperfx-git not found. Abort`
`gst-plugins-good` provides `pulsesrc`, which is needed but not looked out for.

`/etc/viper4linux` does exist, but there are just

- audio.conf 
- audio.conf.template 
- devices.conf.template

So no devices.conf.
Cause of that, deleting the `~/.config/viper4linux/devices.conf` does nothing, 
Everything on one line works, though.

But your preset sounds waay too techno. I'll go experimenting now.

Thanks for your help!

**Comment by yochananmarqos** [comment]
@Baerbeisser What AUR helper did you use to install it? If the dependency `gst-plugin-viperfx-git` was not found, you may be using an old / broken AUR helper.

**Comment by Baerbeisser** [comment]
Pamac should be up to date enough, right?
Other packages from AUR with lots of dependencies like bomi, evince-no-gnome or linux-ck, are resolved correctly.
So it works for you out of the box?

**Comment by yochananmarqos** [comment]
Sometimes `pamac` can't pull dependencies from the AUR. Try an AUR helper like `aurman`, `yay` or `trizen`.
For example:
```
aurman -S viper4linux-git 
```

**Comment by L3vi47h4N** [comment]
Feel free to re-open if this is still unresolved on a supported distro.

**Comment by Baerbeisser** [comment]
I installed now viper4linux with yay on another computer.
It resolved all dependencies correctly, but still no `devices.conf` in /etc/viper4linux.
It works with `devices.conf` and `audio.conf` in ~/.config/viper4linux, though.
Apropos:
`printf 'desc="Speakers" location=%s\n' "$(pactl list sinks | awk '/Name: /{ print $2 }')" >devices.conf`
